[versions]
android-gradle-plugin = "8.9.2"
android-minSdk = "21"
android-compileSdk = "35"
android-buildToolsVersion = "35.0.0"

lib-version = "1.0.0"

kotlin = "2.1.20"

[libraries]

[plugins]
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
